export { ApiClient, ApiClientError, apiClient, getApiClientErrorMessage } from '@/lib/api/client'
export { createFirebaseSession, deleteCurrentSession } from '@/lib/api/auth.service'
export { clearAuthBrowserState, clearStoredAuthObject, getStoredAccessToken, getStoredAuthObject, saveAuthObject } from '@/lib/api/session-storage'
export type { FirebaseSessionResponse, SessionAuth } from '@/lib/api/auth.service'
export type { StoredAuthObject } from '@/lib/api/session-storage'
